/**
 * Generates blog-posts.ndjson for sanity dataset import
 * Run: node scripts/generate-ndjson.mjs
 * Then: cd studio-renova && npx sanity dataset import ../scripts/blog-posts.ndjson production --replace
 */

import { writeFileSync } from 'fs'

let _k = 0
const key  = () => `k${++_k}`
const span = (text) => ({ _type: 'span', _key: key(), text, marks: [] })
const blk  = (style, text) => ({ _type: 'block', _key: key(), style, markDefs: [], children: [span(text)] })

const p  = (t) => blk('normal',     t)
const h2 = (t) => blk('h2',         t)
const h3 = (t) => blk('h3',         t)
const h4 = (t) => blk('h4',         t)
const bq = (t) => blk('blockquote', t)

const disclaimer = bq(
  'All aesthetic procedures carry potential risks and individual results vary. ' +
  'This article provides general information only and does not replace a personal ' +
  'consultation, medical assessment, diagnosis or individual treatment advice.'
)

const posts = [
  {
    _id:   'blog-post-aesthetic-clinic-newcastle',
    _type: 'blogPost',
    title: 'How to Choose an Aesthetic Clinic in Newcastle for Natural-Looking Results',
    slug:  { _type: 'slug', current: 'aesthetic-clinic-newcastle' },
    publishedAt: '2026-07-01T09:00:00Z',
    category: 'Skin Tips',
    featured: false,
    readingTime: 4,
    excerpt: 'Looking for an aesthetic clinic in Newcastle? Discover how Kensley combines personalised consultations, advanced skin treatments and natural-looking care.',
    seo: {
      metaTitle: 'Aesthetic Clinic in Newcastle | Natural Results | Kensley',
      metaDescription: 'Looking for an aesthetic clinic in Newcastle? Discover how Kensley combines personalised consultations, advanced skin treatments and natural-looking care.',
    },
    body: [
      p('Choosing an aesthetic clinic in Newcastle is about more than convenience or trends. The right clinic should explain your skin, discuss realistic outcomes and recommend a plan that respects your features. Most people want to look fresher, not noticeably "treated".'),
      p('A trusted skin clinic Newcastle residents can return to should place consultation and skin health before quick fixes, while reviewing medical history, benefits, limitations, side effects and aftercare.'),
      h2('Start with Your Skin, Not a Trend'),
      p('Every face and skin concern is different. A responsible aesthetic clinic in Newcastle should assess dullness, dehydration, fine lines, uneven texture, volume changes or loss of firmness before recommending treatment. Sometimes one option is suitable; in other cases, a staged plan or professional skincare is more appropriate.'),
      p('A consultation at a skin clinic Newcastle clients trust should consider your lifestyle, previous treatments, budget, downtime and preferred pace of change. This prevents one-size-fits-all recommendations.'),
      h3('Look for a Consultation-Led Treatment Plan'),
      p('Before booking, check whether the clinic provides a proper consultation. At a professional aesthetic clinic in Newcastle, you should be able to explain your concerns and what you want to preserve. A good practitioner will explain when treatment may help, when another option is better, and when no treatment is safest.'),
      p('Your plan should cover recovery, aftercare, review arrangements and clear pricing. A reliable skin clinic Newcastle patients recommend should not pressure you into an immediate decision or promise a perfect result.'),
      h2('Treatments You May Explore at Kensley'),
      p('Kensley Aesthetic Clinic takes a skin-first approach. Depending on suitability, options may include dermal fillers, skin boosters, polynucleotides, biostimulators, medical microneedling, RF microneedling and HIFU-focused skin tightening.'),
      p('The best treatment is not always the newest. At an aesthetic clinic in Newcastle, the priority should be selecting an option that matches your concern, skin condition and expectations. A well-planned skin clinic Newcastle journey may combine in-clinic care with consistent home skincare.'),
      h3('Why Natural-Looking Results Matter'),
      p('Modern aesthetics focuses on subtle improvement. Natural-looking work should support expression and character, not replace them. This may mean improving skin quality first or spacing appointments so changes can be reviewed gradually.'),
      p('At Kensley, treatment planning centres on enhancement rather than transformation, helping clients make informed choices while keeping the focus on confidence and skin health.'),
      h4('What to Check Before You Book'),
      p('When comparing an aesthetic clinic in Newcastle, look beyond photographs. Check practitioner qualifications, experience, consultation quality and how concerns are managed. The clinic should explain suitability, hygiene, consent, aftercare and follow-up support.'),
      p('A professional skin clinic Newcastle residents can trust should avoid exaggerated claims. Before-and-after images may be useful, but individual results vary and should never be presented as a guarantee.'),
      h4('Questions to Ask at Your Consultation'),
      p('Ask why a treatment is recommended, how many sessions may be needed, what downtime to expect, and when results are reviewed. Also ask about risks, alternatives, aftercare and who to contact if you are worried afterwards.'),
      p('The right aesthetic clinic in Newcastle should make you feel informed and comfortable, never rushed.'),
      h2('Why Choosing Local Care Helps'),
      p('Choosing a nearby clinic makes consultations, reviews and ongoing plans easier to maintain, especially when care is spread over several months.'),
      p('Kensley Aesthetic Clinic aims to create a calm, personalised experience for people seeking considered non-surgical care. Whether your priority is hydration, texture, firmness, facial balance or a refreshed appearance, the first step is a consultation focused on your needs.'),
      h3('Begin with an Informed Consultation'),
      p('If you are considering an aesthetic clinic in Newcastle, identify your main concern instead of selecting a procedure from a trend. Bring questions, share relevant health information and allow time to consider the recommendation. A thoughtful plan should feel clear, realistic and tailored.'),
      p('For anyone searching for a skin clinic Newcastle residents can approach for personalised care, Kensley offers consultations designed to explore suitable options and support natural-looking outcomes.'),
      h4('Frequently Asked Questions'),
      p('Q1: What does an aesthetic clinic do?'),
      p('It provides non-surgical options for skin appearance or facial balance, subject to individual assessment.'),
      p('Q2: How do I choose the right clinic?'),
      p('Review credentials, consultation quality, aftercare, hygiene and realistic communication. Do not choose solely on price.'),
      p('Q3: Which treatment is best for my skin?'),
      p('There is no single best treatment. Your skin, history, downtime and goals require assessment.'),
      p('Q4: Will I see results immediately?'),
      p('It depends on the treatment. Some changes appear quickly; others develop gradually. Ask about the expected timeline.'),
      disclaimer,
    ],
  },
  {
    _id:   'blog-post-non-surgical-aesthetic-treatments-newcastle',
    _type: 'blogPost',
    title: 'A Guide to Non-Surgical Aesthetic Treatments Newcastle Clients Can Choose with Confidence',
    slug:  { _type: 'slug', current: 'non-surgical-aesthetic-treatments-newcastle' },
    publishedAt: '2026-07-03T09:00:00Z',
    category: 'Treatments',
    featured: false,
    readingTime: 4,
    excerpt: 'Explore non-surgical aesthetic treatments Newcastle clients can choose for natural-looking results, with consultation-led care at Kensley Aesthetic Clinic.',
    seo: {
      metaTitle: 'Non-Surgical Aesthetic Treatments Newcastle | Kensley',
      metaDescription: 'Explore non-surgical aesthetic treatments Newcastle clients can choose for natural-looking results, with consultation-led care at Kensley Aesthetic Clinic.',
    },
    body: [
      p('Interest in non-surgical aesthetic treatments Newcastle has grown as people seek subtle ways to refresh their appearance without surgery. Start with a careful conversation about your skin, health history and expectations, not a trend.'),
      p('A trusted clinic offering advanced skin treatments Newcastle residents can consider should explain benefits, limits, downtime, risks and aftercare. Planning should feel personal and never rushed.'),
      h2('Understand What Non-Surgical Care Can Address'),
      p('The phrase non-surgical aesthetic treatments Newcastle covers options that may support skin quality, hydration, texture, firmness, facial balance or a rested appearance. They do not involve traditional surgery, but still require proper assessment, technical skill and follow-up.'),
      p('People searching for advanced skin treatments Newcastle may be concerned about dullness, fine lines, uneven texture, acne scarring, reduced firmness or gradual volume change. A consultation clarifies what may improve, what needs another approach and when no treatment is safest.'),
      h3('Choose a Consultation-Led Treatment Plan'),
      p('Before booking non-surgical aesthetic treatments Newcastle, meet the practitioner who will assess you. The consultation should cover previous procedures, medicines, allergies, relevant conditions, lifestyle, budget, downtime and the pace of change you prefer.'),
      p('A responsible provider of advanced skin treatments Newcastle should explain alternatives, side effects, possible complications, recovery and who to contact afterwards. You should have time to decide without pressure from a limited offer.'),
      h2('Treatments You May Explore at Kensley'),
      p('Kensley Aesthetic Clinic takes a personalised, skin-first approach. Depending on suitability, options may include dermal fillers, skin boosters, polynucleotides, biostimulators, medical microneedling, RF microneedling and HIFU-focused skin tightening.'),
      p('When comparing non-surgical aesthetic treatments Newcastle, remember that the newest option is not automatically the best. One person may benefit from hydration and texture support, while another may need a staged plan for firmness, collagen support or facial balance.'),
      h3('Why Natural-Looking Results Matter'),
      p('Modern aesthetic care is centred on restraint. Well-planned advanced skin treatments Newcastle should complement your features and expressions rather than make you look noticeably different. Gradual improvement also allows your response to be reviewed before another session.'),
      p('At Kensley, the purpose of non-surgical aesthetic treatments Newcastle is informed, natural-looking enhancement. Plans should respect facial proportions, skin condition and personal preferences, while recognising that individual results vary.'),
      h4('What to Check Before You Book'),
      p('When researching non-surgical aesthetic treatments Newcastle, look beyond social media images and price promotions. Ask about qualifications, procedure-specific training, experience, insurance, hygiene, consent and complication management. Also understand the product or device being used.'),
      p('A professional clinic providing advanced skin treatments Newcastle should offer clear aftercare and realistic communication. Before-and-after photographs may help, but they should never replace a consultation or imply identical results for everyone.'),
      h4('Questions to Ask at Your Consultation'),
      p('Ask why a treatment is recommended, whether another option may suit you better, how many sessions could be needed and when results can be reviewed. Also ask about discomfort, recovery, maintenance, total cost and what to do if you have concerns.'),
      p('The right provider of non-surgical aesthetic treatments Newcastle should welcome sensible questions, discuss limitations openly and support your choice to take time before proceeding.'),
      h2('Why Choosing Local Care Helps'),
      p('Choosing a Newcastle clinic makes consultations, reviews and longer plans easier to manage. Local continuity is valuable when progress must be assessed over several weeks or when healing and aftercare need review.'),
      p('Kensley Aesthetic Clinic aims to provide a calm, considered experience for adults seeking personalised care. Whether your priority is hydration, texture, firmness, collagen support or facial balance, the first step should be an assessment based on your needs.'),
      h3('Begin with an Informed Consultation'),
      p('Before selecting a procedure, identify your main concern, desired change and acceptable downtime. Share previous treatment details and relevant health information honestly. A thoughtful recommendation should explain suitability, alternatives, risks, timing and aftercare clearly.'),
      p('Kensley offers consultation-led planning to help Newcastle clients explore suitable options with realistic expectations. The aim is not to follow every trend, but to create a treatment journey aligned with personal goals.'),
      h4('Frequently Asked Questions'),
      p('Q1: What are non-surgical aesthetic treatments?'),
      p('They are cosmetic or skin-focused procedures that do not involve traditional surgery. Purpose, technique, recovery and risk vary, so individual assessment matters.'),
      p('Q2: Which treatment is best for skin rejuvenation?'),
      p('There is no universal best option. Skin condition, medical history, downtime and desired outcome influence the recommendation.'),
      p('Q3: How much downtime should I expect?'),
      p('Downtime depends on the procedure and your response. Your practitioner should explain likely redness, swelling, tenderness or activity restrictions beforehand.'),
      p('Q4: How do I choose a suitable practitioner?'),
      p('Check qualifications, training, experience, insurance, consultation quality, aftercare and complication support. Avoid choosing only on price or social media popularity.'),
      disclaimer,
    ],
  },
  {
    _id:   'blog-post-best-non-surgical-aesthetic-clinic-newcastle',
    _type: 'blogPost',
    title: 'How to Find the Best Non-Surgical Aesthetic Clinic in Newcastle',
    slug:  { _type: 'slug', current: 'best-non-surgical-aesthetic-clinic-newcastle' },
    publishedAt: '2026-07-07T09:00:00Z',
    category: 'Skin Tips',
    featured: false,
    readingTime: 4,
    excerpt: 'Looking for the best non-surgical aesthetic clinic in Newcastle? Explore consultation-led care, natural-looking results and personalised planning at Kensley.',
    seo: {
      metaTitle: 'Best Non-Surgical Aesthetic Clinic in Newcastle | Kensley',
      metaDescription: 'Looking for the best non-surgical aesthetic clinic in Newcastle? Explore consultation-led care, natural-looking results and personalised planning at Kensley.',
    },
    body: [
      p('Searching for the best non-surgical aesthetic clinic in Newcastle often begins with photographs, reviews and prices. They do not show the full standard of care. A trustworthy clinic should listen carefully, assess suitability and explain what can realistically be achieved.'),
      p('People comparing aesthetic treatments Newcastle usually want subtle improvement rather than dramatic change. The right experience should combine honest advice, suitable options and dependable aftercare.'),
      h2('Define What "Best" Means for You'),
      p('The best choice is not always the clinic with the biggest following. When looking for the best non-surgical aesthetic clinic in Newcastle, consider whether the practitioner understands your concern, respects your preferences and recommends only suitable care.'),
      p('Your priorities may include hydration, smoother texture, healthier-looking skin, facial balance or support for age-related changes. A clinic providing aesthetic treatments Newcastle should explain whether one session, a course or professional skincare is suitable.'),
      h3('Expect a Thorough, Consultation-Led Assessment'),
      p('A consultation is where personalised planning begins. Before choosing the best non-surgical aesthetic clinic in Newcastle, check that you can meet the practitioner, discuss your history, previous treatments, medicines, allergies and preferred downtime.'),
      p('Good consultations cover benefits, limits, risks, alternatives, pricing and aftercare. Providers of aesthetic treatments Newcastle should also give you time to consider the recommendation without pressure.'),
      h2('Explore Treatment Options with a Skin-First Approach'),
      p('At Kensley Aesthetic Clinic, planning starts with the individual rather than a fashionable procedure. Depending on suitability, options may include dermal fillers, skin boosters, polynucleotides, biostimulators, medical microneedling, RF microneedling and HIFU-focused skin tightening.'),
      p('Someone searching for the best non-surgical aesthetic clinic in Newcastle may arrive with a specific treatment in mind. The plan may instead prioritise skin quality, hydration or collagen support.'),
      h3('Look for Natural-Looking, Proportionate Results'),
      p('Natural-looking care should preserve expression and individual character. Well-planned aesthetic treatments Newcastle can be approached gradually, allowing the response to be reviewed before another session is considered.'),
      p('The best non-surgical aesthetic clinic in Newcastle should not suggest that every face needs the same correction. Thoughtful treatment respects facial proportions, age, skin condition and personal comfort, with realistic expectations about results.'),
      h4('Check Credentials, Hygiene and Aftercare'),
      p("Before booking, ask about professional qualifications, treatment-specific training, experience, insurance and complication management. NHS guidance also recommends checking a cosmetic practitioner's qualifications, experience and insurance. Clean practice, informed consent and clear product information also matter."),
      p('Reliable providers of aesthetic treatments Newcastle should give written aftercare, suitable review arrangements and a contact route for concerns. Avoid choosing solely because of a discount, urgency message or heavily edited image.'),
      h4('Ask Clear Questions Before Making a Decision'),
      p('Ask why the treatment suits your concern, what alternatives exist, how many sessions may be needed and what recovery involves. Also ask when results are reviewed, whether maintenance is expected and what the complete plan may cost.'),
      p('When assessing the best non-surgical aesthetic clinic in Newcastle, notice how your questions are handled. A responsible practitioner should explain uncertainty honestly and advise against treatment when it is unsuitable.'),
      h2('Choose Local Care for Continuity and Convenience'),
      p('For Newcastle residents, a local clinic can make consultations, follow-ups and longer plans easier to manage. This helps when progress or aftercare needs an in-person review.'),
      p('Kensley Aesthetic Clinic aims to provide calm, personalised care for adults seeking considered non-surgical options. Clients exploring aesthetic treatments Newcastle can begin by discussing their concerns, desired outcome, budget and acceptable downtime.'),
      h3('Start with an Informed Consultation at Kensley'),
      p('Finding the best non-surgical aesthetic clinic in Newcastle is ultimately about trust, clinical judgement and communication. Bring questions, share health information and avoid choosing a procedure only because it is popular online.'),
      p('At Kensley, consultation-led planning helps each client understand suitable options and make an unhurried decision. The aim is natural-looking enhancement supported by realistic advice, responsible aftercare and a plan shaped around the person.'),
      h4('Frequently Asked Questions'),
      p('Q1: How can I compare aesthetic clinics in Newcastle?'),
      p('Compare credentials, consultation quality, hygiene, treatment experience, aftercare and communication. Price and photographs should not be your only deciding factors.'),
      p('Q2: Which non-surgical treatment is best for me?'),
      p('There is no universal best treatment. Skin condition, facial structure, health history, expectations and downtime all influence suitability.'),
      p('Q3: Must I book treatment during my consultation?'),
      p('No. You should have time to understand the recommendation, risks, alternatives and total cost before deciding.'),
      p('Q4: Do non-surgical treatments have risks?'),
      p('Yes. Risk and recovery vary. Ask about side effects, complications, aftercare and whom to contact if you have concerns.'),
      disclaimer,
    ],
  },
  {
    _id:   'blog-post-jawline-filler-newcastle',
    _type: 'blogPost',
    title: 'Jawline Filler Newcastle: A Guide to Natural-Looking Definition',
    slug:  { _type: 'slug', current: 'jawline-filler-newcastle' },
    publishedAt: '2026-07-10T09:00:00Z',
    category: 'Treatments',
    featured: false,
    readingTime: 4,
    excerpt: 'Considering jawline filler Newcastle? Explore consultation-led planning, natural-looking definition, risks and aftercare at Kensley Aesthetic Clinic.',
    seo: {
      metaTitle: 'Jawline Filler Newcastle | Natural-Looking Definition | Kensley',
      metaDescription: 'Considering jawline filler Newcastle? Explore consultation-led planning, natural-looking definition, risks and aftercare at Kensley Aesthetic Clinic.',
    },
    body: [
      p('Choosing jawline filler Newcastle is not only about creating a sharper angle. A careful plan considers facial proportions, chin position, profile and how the lower face looks. The aim should be balanced definition that still looks like you.'),
      p('People researching dermal fillers Newcastle may want help with a soft jawline, asymmetry or reduced definition. A consultation clarifies what filler may improve and whether another approach would be more suitable.'),
      h2('What Can Jawline Filler Help Address?'),
      p('A personalised jawline filler Newcastle plan may add subtle structure along selected areas of the lower face. Depending on anatomy, it may support a clearer jaw-to-neck transition, improve chin-and-jaw balance or reduce minor asymmetry.'),
      p('Providers of dermal fillers Newcastle should explain that filler cannot change bone structure, tighten significant loose skin or guarantee a celebrity-style result. Treatment should be based on your features, goals and clinical suitability.'),
      h3('Begin with a Detailed Facial Assessment'),
      p('Before booking jawline filler Newcastle, the practitioner should assess your face at rest and in movement. The consultation should cover medical history, medicines, allergies, previous injectables, dental work, skin health and past complications.'),
      p('A consultation for dermal fillers Newcastle should include benefits, limitations, alternatives, downtime, pricing and aftercare. You should know who will perform the treatment, what product may be used and whom to contact with concerns.'),
      h2('Plan the Jawline as Part of the Whole Face'),
      p('The jawline should not be treated as an isolated line. Chin projection, cheek volume, lower-face width and natural asymmetry affect the final appearance. In some cases, adding more jaw product may not create a balanced outcome.'),
      p('A responsible approach to jawline filler Newcastle may be conservative and staged. The practitioner can prioritise areas offering clear benefit, review how tissues settle and avoid unnecessary volume added only for dramatic photographs.'),
      h3('Aim for Definition, Not Overcorrection'),
      p('Well-planned dermal fillers Newcastle should preserve individuality rather than make every jawline identical. Amount and placement should reflect facial shape, age, skin quality and whether you prefer soft refinement or stronger definition.'),
      p('Results from jawline filler Newcastle vary. Product choice, amount, anatomy and metabolism may affect appearance and longevity. A credible practitioner should avoid promises of perfection and explain whether maintenance or no further treatment is appropriate.'),
      h4('Understand Risks, Products and Aftercare'),
      p("NHS guidance advises checking a practitioner's training, skills, experience and insurance. When considering dermal fillers Newcastle, ask for the product name and source, expected side effects, serious complications, emergency arrangements and written aftercare."),
      p('Swelling, tenderness or bruising may occur after jawline filler Newcastle. Dermal filler complications can also be serious, including infection, nerve damage and, rarely, blindness. Seek prompt advice for unexpected or worsening symptoms.'),
      h4('Ask the Right Questions Before Treatment'),
      p('Ask why filler suits your concern, which areas would be treated, how much product is proposed and whether the plan can be staged. Also ask how the result may look from different angles.'),
      p('When comparing dermal fillers Newcastle, notice whether the practitioner welcomes questions and gives you time to decide. Avoid pressure, online vouchers, rushed consultations or treatment in unsuitable locations.'),
      h2('Choose Local Care for Reviews and Continuity'),
      p('Choosing a local clinic for jawline filler Newcastle can make assessment, aftercare and reviews easier. Continuity allows the practitioner to check healing, compare photographs and decide whether further treatment is appropriate.'),
      p('Kensley Aesthetic Clinic takes a consultation-led approach for adults considering non-surgical facial treatments. Discussion can cover desired definition, previous experiences, budget, downtime and whether a gradual plan is preferable.'),
      h3('Book an Informed Consultation at Kensley'),
      p('A sound decision begins with realistic expectations and clear communication. Bring photographs only as references, share relevant health information and take time to understand the proposed plan before consenting.'),
      p('At Kensley, the goal is natural-looking facial balance supported by individual assessment, measured planning and responsible aftercare. Treatment should proceed only when suitable and when you understand the benefits, limitations and risks.'),
      h4('Frequently Asked Questions'),
      p('Q1: Does jawline filler make the face look slimmer?'),
      p('It may create clearer lower-face definition in suitable clients, but it does not remove fat or tighten significant loose skin. The effect depends on anatomy and planning.'),
      p('Q2: How much jawline filler will I need?'),
      p('There is no standard amount. A practitioner should recommend a conservative quantity based on facial proportions, goals, product choice and whether treatment is staged.'),
      p('Q3: How long do jawline filler results last?'),
      p('Longevity varies between people and products. Your practitioner should explain the expected range for the proposed filler and when a review may be useful.'),
      p('Q4: Must I book treatment during my consultation?'),
      p('No. You should have time to consider the plan, risks, alternatives, aftercare and total cost without pressure.'),
      disclaimer,
    ],
  },
  {
    _id:   'blog-post-lip-filler-newcastle',
    _type: 'blogPost',
    title: 'Lip Filler Newcastle: A Natural-Looking, Consultation-Led Guide',
    slug:  { _type: 'slug', current: 'lip-filler-newcastle' },
    publishedAt: '2026-07-14T09:00:00Z',
    category: 'Treatments',
    featured: true,
    readingTime: 4,
    excerpt: 'Considering lip filler Newcastle? Learn about consultation-led planning, natural-looking results, safety checks and aftercare at Kensley Aesthetic Clinic.',
    seo: {
      metaTitle: 'Lip Filler Newcastle | Natural-Looking Results | Kensley',
      metaDescription: 'Considering lip filler Newcastle? Learn about consultation-led planning, natural-looking results, safety checks and aftercare at Kensley Aesthetic Clinic.',
    },
    body: [
      p('Searching for lip filler Newcastle is often about more than adding volume. You may want softer definition, improved symmetry or a subtle refresh. A responsible plan should begin with your features, preferences and medical history.'),
      p("People comparing dermal fillers Newcastle may see dramatic online photographs, but images cannot show the consultation, technique or aftercare behind a result. Start with an honest discussion about suitability, realistic outcomes and personal boundaries."),
      h2('Decide What You Want to Change'),
      p('Before booking lip filler Newcastle, identify the concern you want to address: a less-defined border, unevenness, age-related volume change or slightly fuller lips. Clear goals help the practitioner recommend a proportionate approach.'),
      p('A clinic offering dermal fillers Newcastle should consider the chin, nose, smile and wider facial structure. Assessment may lead to less product, a staged plan or no treatment.'),
      h3('Begin with a Personal Consultation'),
      p('A consultation for lip filler Newcastle should cover your health, medicines, allergies, previous procedures and reactions. Explain whether you prefer hydration, clearer shape, improved balance or modest fullness.'),
      p('Good providers of dermal fillers Newcastle explain the product, placement, recovery, side effects, complications and alternatives. You should know the total price, review arrangements and who to contact with concerns.'),
      h2('Understand How Lip Filler Is Planned'),
      p('Treatment should follow your anatomy rather than a trend. The practitioner may assess the border, central shape, corners, movement and upper-to-lower-lip relationship before recommending an amount.'),
      p('Someone requesting lip filler Newcastle may assume more product means better results. A gradual plan can support a natural appearance. Results and longevity vary, so treat fixed promises cautiously.'),
      h3('Aim for Balance, Not Maximum Volume'),
      p('Natural-looking dermal fillers Newcastle should respect facial character and expression. Balanced results do not require identical lips. The aim is harmony, not a copied or exaggerated shape.'),
      p("Reference photographs can explain preferences but should not become a template. Another person's lips may not suit your anatomy. A responsible practitioner should explain limitations and reject unsuitable treatment."),
      h4('Check Training, Product and Safety Standards'),
      p('Before choosing lip filler Newcastle, ask about qualifications, training, experience, insurance and complication management. NHS guidance recommends meeting the practitioner and asking what aftercare is available if something goes wrong.'),
      p('Clinics providing dermal fillers Newcastle should identify the product and its source. Clean practice, informed consent, records and timely support matter. Avoid pressure, group events, unrealistic guarantees and social-media popularity alone.'),
      h4('Know What to Expect After Treatment'),
      p('Temporary swelling, tenderness, redness or bruising can occur, and lips may look uneven initially. Follow written aftercare and ask when review is appropriate and which symptoms need urgent attention.'),
      p('Share accurate health information and do not alter medicines without professional advice. Contact the clinic promptly for unexpected pain, colour change, worsening swelling, infection signs or other concerning symptoms.'),
      h2('Choose Local Care for Review and Continuity'),
      p('Choosing lip filler Newcastle locally can simplify consultation, follow-up and review. Continuity helps when swelling needs reassurance, progress requires an in-person check or longer-term treatment is considered.'),
      p('At Kensley Aesthetic Clinic, adults exploring dermal fillers Newcastle can discuss their preferred outcome, downtime and budget. Treatment should proceed only when suitable and when risks and aftercare are understood.'),
      h3('Start with an Informed Consultation at Kensley'),
      p('The right decision about lip filler Newcastle is not based on trends or maximum change. It depends on trust, clear communication and a plan suited to your anatomy. Ask questions and take time to decide.'),
      p('Kensley supports subtle, personalised enhancement through realistic advice and responsible follow-up. An informed consultation helps you understand options without pressure and decide whether treatment is right for you.'),
      h4('Frequently Asked Questions'),
      p('Q1: What can lip filler be used to improve?'),
      p('Depending on suitability, treatment may be considered for subtle fullness, border definition, proportion or visible asymmetry. The approach depends on your anatomy and goals.'),
      p('Q2: How long do lip filler results last?'),
      p('Duration varies between people and products. Your practitioner should explain the likely timeframe, review plan and whether future maintenance may be appropriate.'),
      p('Q3: Will my lips look natural after treatment?'),
      p('Natural-looking results depend on assessment, product choice, technique, the amount used and your starting anatomy. No clinic should guarantee an identical outcome for every client.'),
      p('Q4: What should I ask before booking?'),
      p('Ask about qualifications, experience, insurance, the product used, expected recovery, possible complications, aftercare, review arrangements and the complete cost.'),
      disclaimer,
    ],
  },
]

const ndjson = posts.map(p => JSON.stringify(p)).join('\n')
writeFileSync('scripts/blog-posts.ndjson', ndjson)
console.log('✓ Generated scripts/blog-posts.ndjson')
console.log('\nNow run:')
console.log('  cd studio-renova && npx sanity dataset import ../scripts/blog-posts.ndjson production --replace\n')
